version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: webuser
        uid: 1000
    image: ap-laravel
    container_name: ap-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "${FORWARD_VITE_PORT:-5173}:5173"
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      options:
        max-size: "5k"
    networks:
      - ap

  nginx:
    image: nginx:alpine
    container_name: ap-nginx
    restart: unless-stopped
    ports:
      - "${FORWARD_NGINX_PORT:-80}:80"
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/nginx:/etc/nginx/conf.d
    logging:
      options:
        max-size: "5k"
    networks:
      - ap

  worker-local:
    build:
      context: ./
      dockerfile: dev/docker-compose/worker-local/Dockerfile
      args:
        queueTimeout: 30
        queueTries: 2
        queues: default,indexing,notifications
    image: ap-worker-local
    container_name: ap-worker-local
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./dev/docker-compose/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      options:
        max-size: "5k"
    networks:
      - ap

  mysql:
    image: mysql:8.0
    container_name: ap-mysql
    command: mysqld --sql_mode=""
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dev/docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - ap

  redis:
    build:
      context: ./
      dockerfile: ./dev/docker-compose/redis/Dockerfile
    container_name: ap-redis
    privileged: true
    command: sh -c "/redis/init.sh"
    restart: unless-stopped
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - ./dev/docker-compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: "5k"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      - ap

networks:
  ap:
    driver: bridge
