apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.fullname" . }}-phpfpm
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "laravel-app.selectorLabels" . | nindent 4 }}
    component: phpfpm
  ports:
    - name: fpm
      port: {{ .Values.service.port }}
      targetPort: fpm
      protocol: TCP
